### ISSUE TITLE
[MacOS] User data in Library/Application Support is that right?

### ISSUE THREAD

**Issue by victornpb** [codingjerk/appdirsjs#3]
According to the README, user data is going to be stored in Application Support on MacOS.

https://github.com/codingjerk/appdirsjs/blob/master/README.md?plain=1#L44

But reading the comment which the implemented for MacOS is based seems to suggest the opposite

https://github.com/codingjerk/appdirsjs/blob/master/src/index.ts#L30

<img width="935" alt="image" src="https://user-images.githubusercontent.com/3372598/232657219-887ae80f-300b-4dfd-8021-94dfbb6f29ef.png">

Am I missing something here?

**Comment by victornpb** [comment]
I did more reading and it indeed seems correct to this other documentation 

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/3372598/232672993-f8c3f933-b374-426a-9c44-548554f6932e.png">
from:
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW2:~:text=User%20Experience.-,macOS%20Standard%20Directories%3A%20Where%20Files%20Reside,-Whether%20provided%20by

**Comment by victornpb** [comment]
Yeah, looks like `/Users/User/Library/Preferences/expo` on MacOS is wrong

https://github.com/xdg-rs/dirs/issues/21

https://github.com/dirs-dev/directories-rs

**Comment by codingjerk** [comment]
It is not clear in documentation for me, because of your second message. It seems like there is no alternative to `~/Library/Application Support/<appname>`

**Comment by codingjerk** [comment]
I'm closing this issue for now, but feel free to comment and discuss here
